import 'app/globals.css'
import Navbar from './NavBar/Navbar'
import { Raleway } from "next/font/google";
import About from './About';
import Landing from './Landing';
import React from 'react';
import Projects from './Projects';


const raleway = Raleway({
  subsets: ['latin'],
  weight: ['500']
})

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
      
      <Landing />

      <div className='stuckBar hidden md:block lg:block'>
        <Navbar />
      </div>

      <About />
      <Projects />
      
      {children}
      </body>
    </html>
  )
}

